ASAPMethodology.MvcWebUI/Models/CostOfFutureModel.cs
using ASAPMethodology.Entities.Concrete;

namespace ASAPMethodology.MvcWebUI.Models
{
    public class CostOfFutureModel
    {
        public List<DateTime> PolicyDates { get; set; }
        public List<int> Days { get; set; }
        public List<decimal> DailyPrices { get; set; }
        public List<decimal> MonthlyPrices { get; set; }
        public CostOfFuture CostOfFuture { get; set; }
    }
}

ASAPMethodology.MvcWebUI/Models/ErrorViewModel.cs
namespace ASAPMethodology.MvcWebUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASAPMethodology.MvcWebUI/Controllers/CostOfFutureController.cs
using ASAPMethodology.Business.Abstract;
using ASAPMethodology.Core.Utilities.Results.Abstract;
using ASAPMethodology.Entities.ComplexTypes;
using ASAPMethodology.Entities.Concrete;
using ASAPMethodology.Entities.Dtos;
using ASAPMethodology.MvcWebUI.Models;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace ASAPMethodology.MvcWebUI.Controllers
{
    public class CostOfFutureController : Controller
    {
        private readonly ICostOfFutureService _costOfFutureService;
        private readonly IMapper _mapper;
        private CostOfFutureAddDto _addedCostOfFuture;
        private List<int> _dayMonthNumbers;

        public CostOfFutureController(ICostOfFutureService costOfFutureService, IMapper mapper)
        {
            _costOfFutureService = costOfFutureService;
            _mapper = mapper;
            _addedCostOfFuture = new CostOfFutureAddDto();
            _dayMonthNumbers = new List<int>();
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = new CostOfFutureAddDto
            {
                ExpenseTypeEnums = Enum.GetValues(typeof(ExpenseTypeEnum)).Cast<ExpenseTypeEnum>().ToList(),
                MethodologyTypes = Enum.GetValues(typeof(MethodologyType)).Cast<MethodologyType>().ToList()
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Index(CostOfFutureAddDto costOfFutureAddDto)
        {
            costOfFutureAddDto.ExpenseTypeEnums = Enum.GetValues(typeof(ExpenseTypeEnum)).Cast<ExpenseTypeEnum>().ToList();
            costOfFutureAddDto.MethodologyTypes = Enum.GetValues(typeof(MethodologyType)).Cast<MethodologyType>().ToList();

            var dayMonthNumbers = new List<int> { costOfFutureAddDto.InstallementNo };

            for (int i = 0; i < dayMonthNumbers.Count; i++)
            {
                _dayMonthNumbers.Add(dayMonthNumbers[i]);
            }

            if (ModelState.IsValid)
            {
                var type = costOfFutureAddDto.ExpenseType.ToString()?.Split(",");
                IDataResult<CostOfFutureDto> expenseType = null;
                foreach (var item in type)
                {
                    expenseType = _costOfFutureService.GetByExpenseTypeName(item);
                    if (expenseType == null)
                    {
                        ModelState.AddModelError("Expense type", "Expense Type is not null");
                        return View(costOfFutureAddDto);
                    }
                }
                var mappedExpenseTypeId = _mapper.Map<CostOfFuture>(expenseType);
                var methodologyList = costOfFutureAddDto.MethodologyRadioOptions.ToString()?.Split(",");
                
                _dayMonthNumbers = _dayMonthNumbers.Count(x => x == costOfFutureAddDto.InstallementNo).ToString().Cast<int>().ToList();

                CostOfFuture costOfFuture = new()
                {
                    ExpenseTypeId = mappedExpenseTypeId.Id,
                    CardName = costOfFutureAddDto.CardName,
                    CardLastName = costOfFutureAddDto.CardLastName,
                    DocNum = costOfFutureAddDto.DocNum,
                    PolicyNum = costOfFutureAddDto.PolicyNum,
                    PolicyBegDate = costOfFutureAddDto.PolicyBegDate,
                    InstallementNo = costOfFutureAddDto.InstallementNo,
                    PolicyEndDate = costOfFutureAddDto.PolicyEndDate,
                    Comments = costOfFutureAddDto.Comments,
                    Methodology = methodologyList?.ToString(),
                    InstallementAmount = costOfFutureAddDto.InstallementAmount
                };

                var costOfFutureMap = _mapper.Map<CostOfFutureAddDto>(costOfFuture);
                var result = _costOfFutureService.Add(costOfFutureMap);
                if (result.Success)
                {
                    return RedirectToAction("CalculateList");
                }
                else
                {
                    return View(costOfFutureAddDto);
                }
            }
            return View(costOfFutureAddDto);
        }

        [HttpGet]
        public IActionResult CalculateList()
        {
            var model = new CostOfFutureModel
            {
                Days = _costOfFutureService.DayList(_addedCostOfFuture.PolicyBegDate, _addedCostOfFuture.PolicyEndDate, 
                    _addedCostOfFuture.InstallementNo),
                PolicyDates = _costOfFutureService.PolicyDate(_addedCostOfFuture.PolicyBegDate, _addedCostOfFuture.PolicyEndDate,
                    _addedCostOfFuture.InstallementNo),
                DailyPrices = _costOfFutureService.DailyPrice(_addedCostOfFuture.InstallementAmount, _dayMonthNumbers),
                MonthlyPrices = _costOfFutureService.MonthlyPrice(_addedCostOfFuture.InstallementAmount, _dayMonthNumbers),
            };
            return View(model);
        }
    }
}

ASAPMethodology.MvcWebUI/Controllers/HomeController.cs
using ASAPMethodology.MvcWebUI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ASAPMethodology.MvcWebUI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASAPMethodology.MvcWebUI/Views/CostOfFuture/CalculateList.cshtml
@using System.Text;
@model ASAPMethodology.MvcWebUI.Models.CostOfFutureModel
@{
    ViewData["Title"] = "CalculateList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table table-responsive table-bordered table-hover table-light">
    <thead>
        <tr>
            <th></th>
            <th>Aylık Gün Sayısı</th>
            <th>Günlük Hesaplama</th>
            <th>Aylık Hesaplama</th>
        </tr>
    </thead>
    <tbody>
        @{
            var builder = new StringBuilder();
            @foreach (var policyDate in Model.PolicyDates)
            {
                builder.AppendFormat("<tr>");
                builder.AppendFormat($"<td>{@policyDate}</td>");
            }

            @foreach (var day in Model.Days)
            {
                builder.AppendFormat($"<td>{@day}</td>");
            }

            @foreach (var dailyPrice in Model.DailyPrices)
            {
                builder.AppendFormat($"<td>{@dailyPrice}</td>");
            }

            @foreach (var monthlyPrice in Model.MonthlyPrices)
            {
                builder.AppendFormat($"<td>{@monthlyPrice}</td>");
                builder.AppendFormat("</tr>");
            }
            Html.Raw(builder);
        }
    </tbody>
</table>

ASAPMethodology.MvcWebUI/Views/CostOfFuture/Index.cshtml
@model ASAPMethodology.Entities.Dtos.CostOfFutureAddDto
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form asp-controller="CostOfFuture" asp-action="Index" method="post">
    <div class="form-group">
        <label class="col-sm-4 form-label" asp-for="@Model.ExpenseTypeId">Gider Tipi</label>
        @*<div class="col-sm-2 form-check form-check-inline">
        <input type="checkbox" class="form-check-input" id="chkInsurance">
        <label class="form-check-label" for="chkInsurance">Sigorta</label>
        </div>
        <div class="col-sm-2 form-check form-check-inline">
        <input type="checkbox" class="form-check-input" id="chkPolicy">
        <label class="form-check-label" for="chkPolicy">Kasko</label>
        </div>
        <div class="col-sm-2 form-check form-check-inline">
        <input type="checkbox" class="form-check-input" id="chkRent">
        <label class="form-check-label" for="chkRent">Kira</label>
        </div>*@
        @foreach (var item in Model.ExpenseTypeEnums)
        {
            var expenseTypeIds = "chk" + item;
            <div class="col-sm-2 form-check form-check-inline">
                <input type="checkbox" class="form-check-input" id="@expenseTypeIds" name="ExpenseType" value="@item"/>
                <label class="form-check-label" for="@expenseTypeIds">@item</label>
            </div>
        }
    </div>
    <div class="form-group row mt-3">
        <label asp-for="CardName" class="col-sm-4 form-label">Muhattap Adı</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" asp-for="CardName" placeholder="Muhattap Adı"/>
            <span asp-validation-for="CardName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row mt-3">
        <label asp-for="CardLastName" class="col-sm-4 form-label">Muhattap Soyadı</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" asp-for="CardLastName" placeholder="Muhattap Soyadı"/>
            <span asp-validation-for="CardLastName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row mt-3">
        <label asp-for="PolicyNum" class="col-sm-4 form-label">Poliçe/Sözleşme No</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" asp-for="PolicyNum" placeholder="Poliçe/Sözleşme No"/>
            <span asp-validation-for="PolicyNum" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row mt-3">
        <label asp-for="PolicyBegDate" class="col-sm-4 form-label">Başlangıç Tarihi</label>
        <div class="col-sm-8">
            <input type='date' class="form-control" asp-for="PolicyBegDate" value="@DateTime.Now"/>
            <span asp-validation-for="PolicyBegDate" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row mt-3">
        <label asp-for="InstallementNo" class="col-sm-4 form-label">Taksit Sayısı</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" asp-for="InstallementNo" placeholder="Taksit Sayısı"/>
            <span asp-validation-for="InstallementNo" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row mt-3">
        <label asp-for="PolicyEndDate" class="col-sm-4 form-label">Bitiş Tarihi</label>
        <div class="col-sm-8">
            <input type='date' class="form-control" asp-for="PolicyEndDate" value="@DateTime.Now"/>
            <span asp-validation-for="PolicyEndDate" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row mt-3">
        <label asp-for="Comments" class="col-sm-4 form-label">Açıklamalar</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" asp-for="Comments" placeholder="Açıklamalar"/>
        </div>
    </div>
    <div class="form-group row mt-3">
        <label asp-for="InstallementAmount" class="col-sm-4 form-label">Taksit Tutarı</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" asp-for="InstallementAmount" placeholder="Taksit Tutarı" />
            <span asp-validation-for="InstallementAmount" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group mt-3">
        <label class="col-sm-4 form-label">Hesaplama Yöntemi</label>
        @*<div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="radioDaily">
        <label class="form-check-label">Günlük</label>
        </div>
        <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="radioMontly">
        <label class="form-check-label">Aylık</label>
        </div>*@
        @foreach (var item in Model.MethodologyTypes)
        {
            var methodologyId = "radio" + item;
            <div class="form-check form-check-inline">
                <input type="checkbox" class="form-check-input" id="@methodologyId" name="MethodologyRadioOptions" value="@item">
                <label class="form-check-label" for="@methodologyId">@item</label>
            </div>
        }
    </div>
    <div class="form-group mt-3 d-grid gap-2 col-4 mx-auto">
        <button type="submit" class="btn btn-primary">Hesapla</button>
    </div>
</form>

ASAPMethodology.MvcWebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ASAPMethodology.MvcWebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASAPMethodology</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASAPMethodology.MvcWebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASAPMethodology</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CostOfFuture" asp-action="Index">CostOfFuture</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - ASAPMethodology
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>